# Generated by Django 3.0.2 on 2020-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_fields', models.TextField(verbose_name='Field Value')),
                ('all_fields_ordered', models.TextField(verbose_name='Field Value')),
            ],
        ),
    ]
