# Generated by Django 3.0.2 on 2020-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0005_auto_20200121_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=10000, verbose_name='Field Order Number'),
        ),
    ]
