# Generated by Django 3.0.2 on 2020-01-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0009_auto_20200122_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columnprofilefield',
            unique_together={('column_profile', 'field')},
        ),
    ]
