# Generated by Django 3.0.2 on 2020-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0010_auto_20200122_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Field Name'),
        ),
    ]
