# Generated by Django 3.0.2 on 2020-01-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0011_auto_20200122_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnprofile',
            options={'ordering': ['pk', 'user']},
        ),
        migrations.AlterModelOptions(
            name='columnprofilefield',
            options={'ordering': ['pk', 'column_profile', 'field']},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='productfile',
            options={'ordering': ['uploaded_at']},
        ),
    ]
