# Generated by Django 3.0.2 on 2020-01-31 01:36

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortcode', '0012_auto_20200123_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=31, verbose_name='SKU')),
                ('prev_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Previous Product Data')),
                ('new_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='New Product Data')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), blank=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
