# Generated by Django 3.0.2 on 2020-01-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0013_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='min_length',
            field=models.IntegerField(default=0, verbose_name='Field Min Length'),
        ),
    ]
