# Generated by Django 3.0.2 on 2020-01-31 03:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0014_field_min_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBackup',
            fields=[
                ('sku', models.CharField(max_length=31, primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('part_number', models.CharField(max_length=63, unique=True, verbose_name='SKU')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Product Data')),
            ],
        ),
    ]
