# Generated by Django 3.0.2 on 2020-01-31 06:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0016_product_backup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backup_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Product Data Backup'),
        ),
    ]
