# Generated by Django 3.0.2 on 2020-02-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0022_adminsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='ftp_host',
            field=models.CharField(default='localhost', max_length=127, verbose_name='FTP Host'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='ftp_password',
            field=models.CharField(default='', max_length=63, verbose_name='FTP Password'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='ftp_port',
            field=models.IntegerField(default=22, verbose_name='FTP Port'),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='ftp_user',
            field=models.CharField(default='', max_length=63, verbose_name='FTP User'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='export_path',
            field=models.CharField(default='', max_length=511, verbose_name='Export File Path'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='export_url',
            field=models.CharField(default='', max_length=511, verbose_name='Export Url'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='import_url',
            field=models.CharField(default='https://www.allendale-group.co.uk/shortcode/ShortcodeData.xml', max_length=511, verbose_name='Import Url'),
        ),
    ]
