# Generated by Django 3.0.2 on 2020-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0023_auto_20200213_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetting',
            name='export_path',
            field=models.CharField(blank=True, default='', max_length=511, verbose_name='Export File Path'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='export_url',
            field=models.CharField(blank=True, default='', max_length=511, verbose_name='Export Url'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_host',
            field=models.CharField(blank=True, default='localhost', max_length=127, verbose_name='FTP Host'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_password',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='FTP Password'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_port',
            field=models.IntegerField(blank=True, default=22, verbose_name='FTP Port'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_user',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='FTP User'),
        ),
    ]
