# Generated by Django 3.0.2 on 2020-02-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0024_auto_20200213_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsetting',
            old_name='export_url',
            new_name='ftp_export_path',
        ),
        migrations.RemoveField(
            model_name='adminsetting',
            name='ftp_port',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='active_column_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortcode.ColumnProfile', verbose_name='Active Column Profile'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='export_method',
            field=models.IntegerField(choices=[(0, 'File'), (1, 'Ftp')], default=0, verbose_name='Export Method'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_host',
            field=models.CharField(blank=True, default='', max_length=127, verbose_name='FTP Host'),
        ),
    ]
