# Generated by Django 3.0.2 on 2020-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0025_auto_20200213_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsetting',
            name='ftp_export_path',
            field=models.CharField(blank=True, default='', max_length=511, verbose_name='FTP Export Path'),
        ),
    ]
