# Generated by Django 3.0.2 on 2020-02-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0026_auto_20200214_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='ftp_export_filename',
            field=models.CharField(blank=True, default='', max_length=127, verbose_name='FTP Export File Name'),
        ),
    ]
