# Generated by Django 3.0.2 on 2020-02-27 11:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortcode', '0027_adminsetting_ftp_export_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCodeChange',
            fields=[
                ('part_number', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True, verbose_name='Part Number')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Product Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='Shortcode',
        ),
    ]
